const users = [
    { username: "admin", password: "123" },
    { username: "user", password: "123" },
];

const userActivities = [
    { user_id: 1, action: "Login", timestamp: "2024-11-18T10:00:00Z" },
    { user_id: 2, action: "Verified entity", timestamp: "2024-11-18T11:00:00Z" },
    { user_id: 3, action: "Posted complaint", timestamp: "2024-11-18T12:00:00Z" },
];

const riskScores = [
    { entity_name: "MMM Malaysia", risk_score: 95 },
    { entity_name: "NIKPROFIT TRADING", risk_score: 81 },
    { entity_name: "Omega Pinnacle Ltd (Labuan)", risk_score: 88 },
    { entity_name: "Overseas Commercial Futures (OCFX)", risk_score: 76 },
    { entity_name: "PTFX", risk_score: 92 },
    { entity_name: "Premier Point Market LLC", risk_score: 84 },
    { entity_name: "Premier Point Market Sdn Bhd (1166245-K)", risk_score: 79 },
    { entity_name: "Premier FX Malaysia", risk_score: 89 },
    { entity_name: "Pollywood Scheme", risk_score: 74 },
    { entity_name: "Qinur Enterprise", risk_score: 67 },
    { entity_name: "Questra World (QW)", risk_score: 93 },
    { entity_name: "Rich World Revolution (RWR)", risk_score: 85 },
    { entity_name: "Rex Russel Capital Investment Group", risk_score: 90 },
    { entity_name: "SV International Sdn Bhd (1169355-K)", risk_score: 72 },
    { entity_name: "SV International Scheme", risk_score: 81 },
    { entity_name: "Superbinvest Group", risk_score: 86 },
    { entity_name: "SimplyFX Malaysia", risk_score: 77 },
    { entity_name: "SGV Premier Plan Scheme", risk_score: 92 },
    { entity_name: "SFX Management (KT0339697-V)", risk_score: 70 },
    { entity_name: "TopproFX", risk_score: 88 },
    { entity_name: "Toga Company Limited", risk_score: 95 },
    { entity_name: "Toga Capital Sdn Bhd (1132072-MD)", risk_score: 84 },
    { entity_name: "WMS Global Services (PG0402301-M)", risk_score: 73 },
    { entity_name: "WMS Capital Ltd (Labuan)", risk_score: 91 },
    { entity_name: "XIG Limited", risk_score: 79 },
    { entity_name: "Classic FX Venture", risk_score: 65 },
    { entity_name: "CG International", risk_score: 83 },
    { entity_name: "Carbon Cash Bhd (1218702-K)", risk_score: 76 },
    { entity_name: "FXBITLab Holdings Sdn Bhd (1212832-T)", risk_score: 94 },
    { entity_name: "Forexnova", risk_score: 78 },
    { entity_name: "FBS Malaysia", risk_score: 87 },
    { entity_name: "GTGVIP", risk_score: 80 },
    { entity_name: "Global Tijari Industries Sdn Bhd", risk_score: 82 },
    { entity_name: "Global Tijari Holdings Berhad", risk_score: 89 },
    { entity_name: "IGOFX", risk_score: 91 },
    { entity_name: "Kembara Jutawan Crypto", risk_score: 66 },
    { entity_name: "MyHowk Ling", risk_score: 74 },
    { entity_name: "PTM4U", risk_score: 83 },
    { entity_name: "SVD Malaysia", risk_score: 86 },
    { entity_name: "SMCI Corporation", risk_score: 94 },
    { entity_name: "Sanabil Investment", risk_score: 88 },
    { entity_name: "CYL Prospect Trading", risk_score: 81 },
    { entity_name: "CYL Peoria Enterprise", risk_score: 77 },
    { entity_name: "CYL4U Resources", risk_score: 72 },
    { entity_name: "CYL Asia Enterprise", risk_score: 85 },
    { entity_name: "JJ Online Enterprise (SA0399360K)", risk_score: 68 },
    { entity_name: "JJ Commerce Trading (SA0399365P)", risk_score: 75 },
    { entity_name: "L & L Property Ventures SB (1186992T)", risk_score: 82 },
    { entity_name: "Mama Captain International", risk_score: 90 },
    { entity_name: "NGR Global Sdn Bhd (UT0004411-H)", risk_score: 78 },
    { entity_name: "NGR Asia Group Sdn Bhd (1138129-M)", risk_score: 88 },
    { entity_name: "Nahana Global Resources (00211411-M)", risk_score: 81 },
    { entity_name: "Richway Green Venture (PG0406414M)", risk_score: 80 },
    { entity_name: "Relax Green Enterprise (PG0415537X)", risk_score: 76 },
    { entity_name: "Coin Enterprise Ltd", risk_score: 85 },
    { entity_name: "Climate Protectors Sdn. Bhd", risk_score: 92 },
    { entity_name: "Ecobit", risk_score: 86 },
    { entity_name: "Live Coin Express", risk_score: 93 },
    { entity_name: "Ahmad Zulkhairi Associates PLT (LLP0009065)", risk_score: 73 },
    { entity_name: "Speedline", risk_score: 70 },
    { entity_name: "Slimberry Extreme Team", risk_score: 65 },
    { entity_name: "TukarGold.net", risk_score: 88 },
    { entity_name: "Titan Group Sdn. Bhd (823732-U)", risk_score: 90 },
    { entity_name: "Tabung Dana Ehsan", risk_score: 79 },
    { entity_name: "Virgin Gold Mining Corporation", risk_score: 96 },
    { entity_name: "VC Gold Sdn Bhd (722295-T)", risk_score: 94 },
    { entity_name: "XOC7", risk_score: 78 },
    { entity_name: "Zeta Capital Management", risk_score: 89 },
    { entity_name: "CybertrustFX", risk_score: 81 },
    { entity_name: "Green Forest Global Sdn Bhd (987049-P)", risk_score: 77 },
    { entity_name: "Grand View Golden Success Sdn Bhd (638186-X)- Golden Maximum", risk_score: 83 },
    { entity_name: "Gold Bullion World Sdn Bhd (1018604-A)", risk_score: 91 },
    { entity_name: "Perubatan Islam Seiring Syariat Al-Ikhlas", risk_score: 87 },
    { entity_name: "World Dirham Berhad (970807-X)", risk_score: 85 },
    { entity_name: "Dgreat Network", risk_score: 74 },
    { entity_name: "Danatama Millennium Sdn Bhd (819082-U)", risk_score: 93 },
    { entity_name: "FA Markets", risk_score: 90 },
    { entity_name: "Green Buck Resources Sdn Bhd (851115-A)", risk_score: 84 },
    { entity_name: "Harvest Reliance Consultancy Sdn Bhd (965589-W)", risk_score: 88 },
    { entity_name: "Kelab Kebajikan dan Sosial Tun Teja Malaysia", risk_score: 67 },
    { entity_name: "OLTA Capital Management Inc.", risk_score: 80 },
    { entity_name: "Royale Team Groups", risk_score: 86 },
    { entity_name: "YDS Holding Groups Bhd (987797-T)", risk_score: 79 },
    { entity_name: "YDS Corporate Line Sdn Bhd (877697-P)", risk_score: 82 },
    { entity_name: "Ace Global Sales & Services", risk_score: 83 },
    { entity_name: "APS Asia Plantation Sdn Bhd (984575-T)", risk_score: 90 },
    { entity_name: "Build Rich Mining Group Bhd (1006586-T)", risk_score: 92 },
    { entity_name: "E-Qirad Sdn Bhd (595699-D)", risk_score: 76 },
    { entity_name: "Epic Palms Bhd", risk_score: 89 },
    { entity_name: "LS Gold Bullion Sdn Bhd (235435-H)", risk_score: 94 },
    { entity_name: "Nexgain Malaysia Sdn Bhd (773854-D)", risk_score: 85 },
    { entity_name: "Premier Ventures Gold", risk_score: 78 },
    { entity_name: "Amazing Yields Sdn Bhd (891529-V)", risk_score: 87 },
    { entity_name: "Dynamic Wira Marketing Sdn Bhd - Skim Beras 1 Malaysia", risk_score: 81 },
    { entity_name: "Energetic Gateway Sdn Bhd (511826-X)", risk_score: 74 },
    { entity_name: "Preferred Credentials Sdn Bhd", risk_score: 88 },
    { entity_name: "Sera Land Management & Enterprise (JM0503206-P)", risk_score: 70 },
    { entity_name: "The Gold Guarantee", risk_score: 92 },
    { entity_name: "CTK Network", risk_score: 86 },
    { entity_name: "Ultimate Power Profits", risk_score: 78 },
    { entity_name: "WSL Merchants Pte Ltd", risk_score: 81 },
    { entity_name: "CGF Fine Metal Sdn Bhd", risk_score: 75 },
    { entity_name: "Eagle Aeronautics (M) Sdn Bhd (796603-A)", risk_score: 84 },
    { entity_name: "Future Trade Indojaya Sdn Bhd (1003327-P)", risk_score: 94 },
    { entity_name: "Greenmillion Agrosolution Enterprise", risk_score: 83 },
    { entity_name: "Global Peace Loving Family", risk_score: 77 },
    { entity_name: "Royal Gold Sdn Bhd (1005830-X)", risk_score: 95 },
    { entity_name: "SGFM Trading Sdn Bhd (936419-V)", risk_score: 79 },
    { entity_name: "Urustabil Sdn Bhd (545426-X)", risk_score: 90 },
    { entity_name: "Great Access Sdn Bhd (517965-X)", risk_score: 85 },
    { entity_name: "AU79 International", risk_score: 88 },
    { entity_name: "AU Niaga Sdn Bhd (907806-W)", risk_score: 83 },
    { entity_name: "Al-Saliha Worlwide Sdn. Bhd. (628267-M)", risk_score: 91 },
    { entity_name: "1Gold.com.my", risk_score: 77 },
    { entity_name: "1globalcash", risk_score: 67 },
    { entity_name: "Bumi Klasik Warisan Enterprise", risk_score: 86 },
    { entity_name: "DNA Profile Sdn Bhd (245435-W)", risk_score: 70 },
    { entity_name: "Degold Empire Sdn Bhd (882335-M)", risk_score: 79 },
    { entity_name: "Dana Haji Jasman", risk_score: 93 },
    { entity_name: "Ezey Marketing", risk_score: 78 },
    { entity_name: "Extra Capital Programme", risk_score: 88 },
    { entity_name: "East Cape Mining Corp", risk_score: 94 },
    { entity_name: "FNZ Capital Limited", risk_score: 90 },
    { entity_name: "Flexsy Enterprise & Barrilorne Corp", risk_score: 87 },
    { entity_name: "FE Brands (M) Sdn Bhd (1000656-H)", risk_score: 81 },
    { entity_name: "Gorgeous Chain Sdn Bhd (841928-P)", risk_score: 75 },
    { entity_name: "Global Venture Financing", risk_score: 84 },
    { entity_name: "Global Creation Trading", risk_score: 82 },
    { entity_name: "GGF Golden House Sdn Bhd (803753-W)", risk_score: 88 },
    { entity_name: "Gan Patt Services", risk_score: 73 },
    { entity_name: "Gain FX Capital Sdn Bhd", risk_score: 92 },
    { entity_name: "Honest Group Ltd", risk_score: 78 },
    { entity_name: "Hexa Commerce Sdn Bhd (645798-X)", risk_score: 89 },
    { entity_name: "Isothree Gold Sdn Bhd (906561-K)", risk_score: 94 },
    { entity_name: "Instaforex", risk_score: 96 },
    { entity_name: "IGC Diamond", risk_score: 80 },
    { entity_name: "Iconhill Holding Sdn Bhd (810775-P)", risk_score: 79 },
    { entity_name: "JTGold", risk_score: 85 },
    { entity_name: "JMI Global", risk_score: 88 },
    { entity_name: "JM Communications & Technology Sdn Bhd (702054-V)", risk_score: 83 },
    { entity_name: "Jazlaan Enterprise", risk_score: 66 },
    { entity_name: "Jalatama Management Sdn Bhd (929594-W)", risk_score: 74 },
    { entity_name: "Kris Plus Enterprise (IP0238424-A)", risk_score: 77 },
    { entity_name: "LocalAdClick", risk_score: 80 },
    { entity_name: "Life Time Holidays Sdn Bhd (727129-U)", risk_score: 87 },
    { entity_name: "Liberty Reserve", risk_score: 91 },
    { entity_name: "Lestari2U", risk_score: 82 },
    { entity_name: "Megaherbs Bioextreme (001946380-K)", risk_score: 76 },
    { entity_name: "Mega Dynasty Sdn Bhd (931589-V)", risk_score: 89 },
    { entity_name: "Mari Wholesale (M) Sdn Bhd (556117-T)", risk_score: 70 },
    { entity_name: "One AutoCash", risk_score: 79 },
    { entity_name: "Provisio Multimedia", risk_score: 87 },
    { entity_name: "Projek Duit 2012", risk_score: 85 },
    { entity_name: "Program I-Rich", risk_score: 93 },
    { entity_name: "Program 10 Bulan Forex Trading", risk_score: 92 },
    { entity_name: "Prestige Dairy Farm (M) Berhad (832757-A)", risk_score: 90 },
    { entity_name: "Pars Pay Sdn Bhd (813378-V)", risk_score: 78 },
    { entity_name: "Pancar Mayang Sdn Bhd (527196-H)", risk_score: 87 },
    { entity_name: "RS Capital Holdings Bhd (819833-P)", risk_score: 84 },
    { entity_name: "Rowther Technologies MSC Sdn Bhd (727979-T)", risk_score: 74 },
    { entity_name: "RMMUDAH.COM", risk_score: 65 },
    { entity_name: "RGCX Trading Corp", risk_score: 89 },
    { entity_name: "Real Ingenious Sdn Bhd (926598-U)", risk_score: 92 },
    { entity_name: "Syarikat Sri Alam", risk_score: 82 },
    { entity_name: "Syarikat GECS Ltd", risk_score: 75 },
    { entity_name: "Swiss Capital Venture", risk_score: 93 },
    { entity_name: "Suliz Pearl Mines", risk_score: 85 },
    { entity_name: "Sri Perkasa Emas Trading", risk_score: 83 },
    { entity_name: "Norry Setia Ent (TR0103958-M)", risk_score: 70 },
    { entity_name: "Nory Motor (TR0023237-H)", risk_score: 73 },
    { entity_name: "Overseas Delight Sdn Bhd (614245-W)", risk_score: 88 },
    { entity_name: "Puncak Hartawan Resources (0000097980-T)", risk_score: 87 },
    { entity_name: "Pro Infinity Ltd", risk_score: 92 },
    { entity_name: "RM20segera.com", risk_score: 74 },
    { entity_name: "Rimbun Tekad Consultancy Sdn Bhd (966620-V)", risk_score: 83 },
    { entity_name: "Rimbun Tekad Realty Sdn Bhd (966604-D)", risk_score: 86 },
    { entity_name: "Rejabwealth Sdn Bhd (1005424-X)", risk_score: 81 },
    { entity_name: "Rejab Trading (TR0115248-A)", risk_score: 77 },
    { entity_name: "Sri Chempaka Emas Enterprise (SA0293336-P)", risk_score: 82 },
    { entity_name: "Tenaga Setia Services (107239-P)", risk_score: 68 },
    { entity_name: "Tanjung Trading (TR0123942-W)", risk_score: 76 },
    { entity_name: "Uncang Teguh Resources (0000102116-T)", risk_score: 85 },
    { entity_name: "UFUNCLUB", risk_score: 96 },
    { entity_name: "UER Gold", risk_score: 91 },
    { entity_name: "Verger Management Services", risk_score: 89 },
    { entity_name: "Water World Marketing (CA0177161-P)", risk_score: 77 },
    { entity_name: "Alpari (Asian) Ltd", risk_score: 93 },
    { entity_name: "Sejati Agarwood Enterprise", risk_score: 80 },
    { entity_name: "Empire Five Trading", risk_score: 78 },
    { entity_name: "Kelab Kebajikan Sosial Malaysia (VVIP88)", risk_score: 90 },
    { entity_name: "Meccafund Family Malaysia", risk_score: 85 },
    { entity_name: "PPC Storm", risk_score: 70 },
    { entity_name: "Pegasus Bullion", risk_score: 83 },
    { entity_name: "Axis Capital Corporation Ltd", risk_score: 92 },
    { entity_name: "Build Rich Enterprise", risk_score: 89 },
    { entity_name: "Build Rich Agrotech Berhad", risk_score: 87 },
    { entity_name: "Build Rich Group Holding", risk_score: 84 },
    { entity_name: "Build Rich Investment Group Ltd", risk_score: 81 },
    { entity_name: "Cash Deal Sdn Bhd (Boss Venture)", risk_score: 86 },
    { entity_name: "Darul Emas Perak Bhd", risk_score: 88 },
    { entity_name: "Public Golden House Sdn Bhd (806825-M)", risk_score: 91 },
    { entity_name: "Pevoni Development Sdn Bhd", risk_score: 80 },
    { entity_name: "Profitable Plots Pte Ltd", risk_score: 96 },
    { entity_name: "Quantum Asset (002275903-T)", risk_score: 74 },
    { entity_name: "Prominent Axis Sdn Bhd (002303163-K)", risk_score: 90 },
    { entity_name: "Prime Global Vision", risk_score: 92 },
    { entity_name: "QCFD", risk_score: 83 },
    { entity_name: "RealFX", risk_score: 85 },
    { entity_name: "RB Forex (FM0357971-D)", risk_score: 88 },
    { entity_name: "Royale Gold Wealth Scheme", risk_score: 80 },
    { entity_name: "Ristanna Golden House", risk_score: 92 },
    { entity_name: "Skill-Plus Global Sdn Bhd (1224164-D)", risk_score: 87 },
    { entity_name: "Softlux Sdn Bhd", risk_score: 93 },
    { entity_name: "Storm Venture", risk_score: 78 },
    { entity_name: "Stream Global Enterprise", risk_score: 81 },
    { entity_name: "Steady Mart Resources (JM0637256-D)", risk_score: 70 },
    { entity_name: "Sumur Emas Trading (TR0097243-D)", risk_score: 85 },
    { entity_name: "TP Golden Venture", risk_score: 90 },
    { entity_name: "TTS Trading (PG0412347-M)", risk_score: 88 },
    { entity_name: "UAG GOLD", risk_score: 94 },
    { entity_name: "Venture Grand Enterprise (1046722-D)", risk_score: 84 },
    { entity_name: "Wesley Gold", risk_score: 87 },
    { entity_name: "Wellgold Venture Sdn Bhd", risk_score: 91 },
    { entity_name: "Winspire Capital", risk_score: 85 },
    { entity_name: "Waterfall Project Ltd", risk_score: 88 },
    { entity_name: "Zee Golden Ventures", risk_score: 86 }
];

const verify = [
    { type: "business", value: "ABC Ltd.", entity_name: "ABC Ltd.", match_score: 83, frequency_score: 4, complaint_count: 1 },
    { type: "business", value: "XYZ Ltd.", entity_name: "XYZ Ltd.", match_score: 75, frequency_score: 3, complaint_count: 2 },
    { type: "business", value: "FraudCo", entity_name: "FraudCo", match_score: 95, frequency_score: 5, complaint_count: 4 },
    { type: "business", value: "Eagle Aeronautics (M) Sdn Bhd (796603-A)", entity_name: "Eagle Aeronautics (M) Sdn Bhd (796603-A)", match_score: 84, frequency_score: 3, complaint_count: 2 },
    { type: "business", value: "Future Trade Indojaya Sdn Bhd (1003327-P)", entity_name: "Future Trade Indojaya Sdn Bhd (1003327-P)", match_score: 91, frequency_score: 5, complaint_count: 3 },
    { type: "business", value: "Greenmillion Agrosolution Enterprise", entity_name: "Greenmillion Agrosolution Enterprise", match_score: 77, frequency_score: 4, complaint_count: 1 },
    { type: "phone", value: "1234567890", entity_name: "John Doe", match_score: 79, frequency_score: 2, complaint_count: 0 },
    { type: "account", value: "0011223344", entity_name: "ABC Ltd.", match_score: 82, frequency_score: 3, complaint_count: 2 },
    { type: "account", value: "9876543210", entity_name: "FraudCo", match_score: 96, frequency_score: 5, complaint_count: 3 },
    { type: "phone", value: "5551234567", entity_name: "XYZ Ltd.", match_score: 80, frequency_score: 4, complaint_count: 2 },
    { type: "business", value: "Royal Gold Sdn Bhd (1005830-X)", entity_name: "Royal Gold Sdn Bhd (1005830-X)", match_score: 95, frequency_score: 4, complaint_count: 3 },
    { type: "account", value: "1100332233", entity_name: "Global Peace Loving Family", match_score: 85, frequency_score: 4, complaint_count: 1 },
    { type: "business", value: "Urustabil Sdn Bhd (545426-X)", entity_name: "Urustabil Sdn Bhd (545426-X)", match_score: 90, frequency_score: 5, complaint_count: 2 },
    { type: "phone", value: "4411223344", entity_name: "Greenmillion Agrosolution Enterprise", match_score: 82, frequency_score: 2, complaint_count: 0 },
    { type: "account", value: "9988776655", entity_name: "SGFM Trading Sdn Bhd (936419-V)", match_score: 78, frequency_score: 4, complaint_count: 3 },
    { type: "business", value: "JTGold", entity_name: "JTGold", match_score: 85, frequency_score: 3, complaint_count: 1 },
    { type: "phone", value: "7788991122", entity_name: "Great Access Sdn Bhd (517965-X)", match_score: 87, frequency_score: 2, complaint_count: 1 },
    { type: "business", value: "Iconhill Holding Sdn Bhd (810775-P)", entity_name: "Iconhill Holding Sdn Bhd (810775-P)", match_score: 79, frequency_score: 3, complaint_count: 2 },
    { type: "account", value: "6655443322", entity_name: "Instaforex", match_score: 96, frequency_score: 5, complaint_count: 4 },
    { type: "phone", value: "3322114455", entity_name: "Hexa Commerce Sdn Bhd (645798-X)", match_score: 89, frequency_score: 4, complaint_count: 2 },
    { type: "business", value: "Isothree Gold Sdn Bhd (906561-K)", entity_name: "Isothree Gold Sdn Bhd (906561-K)", match_score: 94, frequency_score: 5, complaint_count: 3 },
    { type: "account", value: "2211334455", entity_name: "RealFX", match_score: 85, frequency_score: 3, complaint_count: 1 },
    { type: "phone", value: "9911223344", entity_name: "Overseas Delight Sdn Bhd (614245-W)", match_score: 88, frequency_score: 4, complaint_count: 2 },
    { type: "business", value: "Prime Global Vision", entity_name: "Prime Global Vision", match_score: 92, frequency_score: 5, complaint_count: 3 },
    { type: "account", value: "1231231231", entity_name: "Ristanna Golden House", match_score: 92, frequency_score: 4, complaint_count: 1 },
    { type: "phone", value: "3322334455", entity_name: "UFUNCLUB", match_score: 96, frequency_score: 5, complaint_count: 4 },
    { type: "business", value: "Public Golden House Sdn Bhd (806825-M)", entity_name: "Public Golden House Sdn Bhd (806825-M)", match_score: 91, frequency_score: 4, complaint_count: 3 },
    { type: "account", value: "5566778899", entity_name: "Darul Emas Perak Bhd", match_score: 88, frequency_score: 3, complaint_count: 2 },
    { type: "phone", value: "7788445566", entity_name: "Real Ingenious Sdn Bhd (926598-U)", match_score: 92, frequency_score: 4, complaint_count: 1 },
    { type: "business", value: "Softlux Sdn Bhd", entity_name: "Softlux Sdn Bhd", match_score: 93, frequency_score: 5, complaint_count: 4 }
];

const forumPosts = [
    {
        post_id: 1,
        user: "AhmadRazak",
        title: "Stay away from Instaforex!",
        content: "Instaforex scammed me out of RM5000 with their fake investment schemes.",
        likes: 12,
        dislikes: 3,
        comments: [
            { user: "NurAisyah", content: "I almost invested with them. Thanks for the warning!" },
            { user: "Farhan", content: "They targeted my cousin too. It's terrible." },
        ],
    },
    {
        post_id: 2,
        user: "SitiHana",
        title: "Scam alert: JTGold",
        content: "JTGold is running a fake gold investment scheme. Be cautious.",
        likes: 9,
        dislikes: 1,
        comments: [
            { user: "AliFikri", content: "I lost RM2000 with them. Never again!" },
            { user: "Zarina", content: "These scams are getting worse." },
        ],
    },
    {
        post_id: 3,
        user: "RahimAhmad",
        title: "Phone scam from 60123456789",
        content: "Received a call from this number claiming to be from Royal Gold Sdn Bhd. It’s a scam!",
        likes: 7,
        dislikes: 2,
        comments: [
            { user: "Aminah", content: "I got the same call. Blocked them immediately." },
            { user: "Shafiq", content: "They are so persistent. Thanks for sharing." },
        ],
    },
    {
        post_id: 4,
        user: "Zulkhairi",
        title: "Avoid Urustabil Sdn Bhd!",
        content: "Urustabil Sdn Bhd promised high returns but disappeared with my money.",
        likes: 15,
        dislikes: 4,
        comments: [
            { user: "Lina", content: "They scammed my entire family. Disgusting!" },
            { user: "Rizal", content: "Let's report them to the authorities." },
        ],
    },
    {
        post_id: 5,
        user: "Alya",
        title: "Greenmillion Agrosolution: Another scam!",
        content: "They approached me with an 'agriculture investment' that was too good to be true.",
        likes: 10,
        dislikes: 2,
        comments: [
            { user: "Faiz", content: "I saw their ads on Facebook. Thanks for the heads-up!" },
            { user: "Mimi", content: "Why are these scams not shut down yet?" },
        ],
    },
    {
        post_id: 6,
        user: "Farid",
        title: "Fraud alert: Overseas Delight Sdn Bhd",
        content: "They took my RM10,000 and claimed it was for 'business expansion.' Total fraud!",
        likes: 20,
        dislikes: 5,
        comments: [
            { user: "Salina", content: "This is heartbreaking. Hope you recover your money." },
            { user: "Hafiz", content: "I was skeptical about them. Glad I didn't invest." },
        ],
    },
    {
        post_id: 7,
        user: "Liyana",
        title: "Beware of Build Rich Mining Group Bhd",
        content: "This company lures people into a fake mining scheme. Stay away!",
        likes: 8,
        dislikes: 1,
        comments: [
            { user: "Ismail", content: "I lost RM5000 to them. Be cautious." },
            { user: "Nadia", content: "Thanks for the info. I almost fell for it." },
        ],
    },
    {
        post_id: 8,
        user: "Amir",
        title: "Warning: Dana Haji Jasman",
        content: "They promised high returns and disappeared. Another Ponzi scheme.",
        likes: 11,
        dislikes: 3,
        comments: [
            { user: "Fadhil", content: "My neighbor was tricked by them. So sad." },
            { user: "Zainab", content: "Why are these scams always targeting Malaysians?" },
        ],
    },
    {
        post_id: 9,
        user: "Nora",
        title: "Fraudulent calls from 60198765432",
        content: "Claiming to be from Premier FX Malaysia. Do not trust them!",
        likes: 6,
        dislikes: 0,
        comments: [
            { user: "Hakim", content: "I received the same call. Thanks for sharing!" },
            { user: "Aziz", content: "Blocked them as soon as they called." },
        ],
    },
    {
        post_id: 10,
        user: "Hana",
        title: "Avoid Global Tijari Holdings Berhad",
        content: "They are running a fake investment scheme and tricking people.",
        likes: 13,
        dislikes: 2,
        comments: [
            { user: "Iman", content: "My cousin lost RM8000 to them. Beware!" },
            { user: "Sufi", content: "Thank you for exposing them. Reporting to Bank Negara." },
        ],
    },
];


const newsPosts = [
    {
        post_id: 1,
        user: "JohnDoe",
        title: "Suspicious company spotted",
        content: "This company has been involved in fraud cases."
    },
    {
        post_id: 2,
        user: "Alice",
        title: "Beware of this phone number",
        content: "Received multiple scam calls from 1234567890."
    },
    {
        post_id: 2,
        user: "Alice",
        title: "Beware of this phone number",
        content: "Received multiple scam calls from 1234567890."
    },
];

const tickets = [
    {
        caseId: "C101",
        victimName: "Ahmad Zahari",
        contact: "60123456789",
        email: "ahmadz@example.com",
        caseDescription: "Lost RM5000 in a fake investment by Instaforex.",
        companyName: "Instaforex",
        phone: "60198765432",
        accountNumber: "123456789012",
        status: "Open",
        updates: "Initial investigation started.",
        chatHistory: [
            { sender: "Victim", message: "I invested and now they are unreachable." },
            { sender: "Officer", message: "We have noted your complaint and are investigating." },
        ],
    },
    {
        caseId: "C102",
        victimName: "Nur Hana",
        contact: "60145678912",
        email: "nurhana@example.com",
        caseDescription: "Received scam calls from Premier FX Malaysia.",
        companyName: "Premier FX Malaysia",
        phone: "60112345678",
        accountNumber: "987654321123",
        status: "In Progress",
        updates: "Scam source traced to a fake office.",
        chatHistory: [
            { sender: "Victim", message: "They keep calling and asking for my details." },
            { sender: "Officer", message: "We recommend blocking the number for now." },
        ],
    },
    {
        caseId: "C103",
        victimName: "Farid Ahmad",
        contact: "60178912345",
        email: "faridahmad@example.com",
        caseDescription: "Lost RM10,000 in a scam by Urustabil Sdn Bhd.",
        companyName: "Urustabil Sdn Bhd",
        phone: "60187654321",
        accountNumber: "654321098765",
        status: "Open",
        updates: "Complaint forwarded to enforcement division.",
        chatHistory: [
            { sender: "Victim", message: "Their scheme seemed legitimate at first." },
            { sender: "Officer", message: "We are working to recover your funds." },
        ],
    },
    {
        caseId: "C104",
        victimName: "Siti Nurhaliza",
        contact: "60187654321",
        email: "sitinur@example.com",
        caseDescription: "Fraudulent charges by Royal Gold Sdn Bhd.",
        companyName: "Royal Gold Sdn Bhd",
        phone: "60191234567",
        accountNumber: "345678901234",
        status: "Resolved",
        updates: "Funds partially recovered.",
        chatHistory: [
            { sender: "Victim", message: "I noticed unauthorized charges on my account." },
            { sender: "Officer", message: "We’ve recovered RM5000 and will contact you for disbursement." },
        ],
    },
    {
        caseId: "C105",
        victimName: "Rizal Hakim",
        contact: "60199887766",
        email: "rizalhakim@example.com",
        caseDescription: "Investment scam by JTGold.",
        companyName: "JTGold",
        phone: "60133445566",
        accountNumber: "112233445566",
        status: "Open",
        updates: "Gathering evidence for legal action.",
        chatHistory: [
            { sender: "Victim", message: "I was promised high returns, but nothing came through." },
            { sender: "Officer", message: "Can you share all communications with them?" },
        ],
    },
    {
        caseId: "C106",
        victimName: "Ali Fikri",
        contact: "60133445577",
        email: "alifikri@example.com",
        caseDescription: "Phone scam involving Global Tijari Holdings Berhad.",
        companyName: "Global Tijari Holdings Berhad",
        phone: "60188776655",
        accountNumber: "998877665544",
        status: "In Progress",
        updates: "Tracing the scammer’s phone records.",
        chatHistory: [
            { sender: "Victim", message: "They asked for my bank details over the phone." },
            { sender: "Officer", message: "We advise you to avoid sharing personal details." },
        ],
    },
    {
        caseId: "C107",
        victimName: "Halimah",
        contact: "60122334455",
        email: "halimah@example.com",
        caseDescription: "Fraudulent transactions by Build Rich Mining Group Bhd.",
        companyName: "Build Rich Mining Group Bhd",
        phone: "60199887744",
        accountNumber: "443322110055",
        status: "Open",
        updates: "Requesting additional details from the victim.",
        chatHistory: [
            { sender: "Victim", message: "They took RM15,000 and never responded." },
            { sender: "Officer", message: "Please provide any payment receipts for evidence." },
        ],
    },
    {
        caseId: "C108",
        victimName: "Nadia Shams",
        contact: "60155667788",
        email: "nadiashams@example.com",
        caseDescription: "Scam by Greenmillion Agrosolution Enterprise.",
        companyName: "Greenmillion Agrosolution Enterprise",
        phone: "60199887722",
        accountNumber: "667788990011",
        status: "Open",
        updates: "Investigating the company’s claims.",
        chatHistory: [
            { sender: "Victim", message: "I trusted them because of their agriculture story." },
            { sender: "Officer", message: "We will verify their business registration." },
        ],
    },
    {
        caseId: "C109",
        victimName: "Syafiq Zul",
        contact: "60188776699",
        email: "syafiqzul@example.com",
        caseDescription: "Fake gold scheme by Norry Setia Ent.",
        companyName: "Norry Setia Ent",
        phone: "60199887733",
        accountNumber: "998877665533",
        status: "In Progress",
        updates: "Collecting reports from other victims.",
        chatHistory: [
            { sender: "Victim", message: "They claimed to sell genuine gold but disappeared." },
            { sender: "Officer", message: "Do you have their advertisements or receipts?" },
        ],
    },
    {
        caseId: "C110",
        victimName: "Zarina Hashim",
        contact: "60199887711",
        email: "zarina@example.com",
        caseDescription: "Scam calls from Dana Haji Jasman.",
        companyName: "Dana Haji Jasman",
        phone: "60144332211",
        accountNumber: "112233445577",
        status: "Open",
        updates: "Tracing their network activities.",
        chatHistory: [
            { sender: "Victim", message: "They asked me to transfer RM3000 for a ‘processing fee.’" },
            { sender: "Officer", message: "Do not transfer any money. We are on it." },
        ],
    },
    {
        caseId: "C111",
        victimName: "Laila Amin",
        contact: "60166554422",
        email: "laila@example.com",
        caseDescription: "Fraudulent activities by Overseas Delight Sdn Bhd.",
        companyName: "Overseas Delight Sdn Bhd",
        phone: "60188776622",
        accountNumber: "223344556677",
        status: "In Progress",
        updates: "Legal action underway.",
        chatHistory: [
            { sender: "Victim", message: "They advertised as a trusted international company." },
            { sender: "Officer", message: "We’re coordinating with international authorities." },
        ],
    },
    {
        caseId: "C112",
        victimName: "Aminah Sharif",
        contact: "60199887777",
        email: "aminah@example.com",
        caseDescription: "Investment scam by Swiss Capital Venture.",
        companyName: "Swiss Capital Venture",
        phone: "60144332277",
        accountNumber: "665544332211",
        status: "Open",
        updates: "Evidence gathering in progress.",
        chatHistory: [
            { sender: "Victim", message: "They promised 20% monthly returns. Total scam!" },
            { sender: "Officer", message: "We’ve flagged them as high-risk." },
        ],
    },
    {
        caseId: "C113",
        victimName: "Ismail Yusuf",
        contact: "60133445588",
        email: "ismailyusuf@example.com",
        caseDescription: "Fraudulent calls pretending to be from FA Markets.",
        companyName: "FA Markets",
        phone: "60155443388",
        accountNumber: "332211445566",
        status: "Open",
        updates: "Fraud alert issued to the public.",
        chatHistory: [
            { sender: "Victim", message: "They asked for my bank OTP. I didn’t share it." },
            { sender: "Officer", message: "Good move. Always verify the source before sharing details." },
        ],
    },
    {
        caseId: "C114",
        victimName: "Rahmat Ibrahim",
        contact: "60177889966",
        email: "rahmat@example.com",
        caseDescription: "Scam by Live Coin Express.",
        companyName: "Live Coin Express",
        phone: "60166554499",
        accountNumber: "445566778899",
        status: "In Progress",
        updates: "Contacting associated banks for account freezing.",
        chatHistory: [
            { sender: "Victim", message: "They asked for an upfront fee to release funds." },
            { sender: "Officer", message: "Avoid all interactions with them. We’re on it." },
        ],
    },
    {
        caseId: "C115",
        victimName: "Hafiz Ramlan",
        contact: "60111223344",
        email: "hafizramlan@example.com",
        caseDescription: "Fraudulent charges by Kasih Bumi Ventures.",
        companyName: "Kasih Bumi Ventures",
        phone: "60199887755",
        accountNumber: "556677889900",
        status: "Resolved",
        updates: "Funds fully recovered and returned.",
        chatHistory: [
            { sender: "Victim", message: "They charged me without authorization." },
            { sender: "Officer", message: "We’ve recovered the funds. Please check your account." },
        ],
    },
];

  
  
const updateTicket = (caseId, updateDetails) => {
    const ticket = tickets.find((t) => t.caseId === caseId);
    if (ticket) {
      ticket.updates = (ticket.updates || "") + " " + updateDetails;
      return ticket.updates;
    }
    return null;
};
  
const addChatMessage = (caseId, chatMessage) => {
    const ticket = tickets.find((t) => t.caseId === caseId);
    if (ticket) {
      ticket.chatHistory = ticket.chatHistory || [];
      ticket.chatHistory.push(chatMessage);
      return true;
    }
    return false;
};


const getUsers = () => users;
const getUserActivities = () => userActivities;
const getRiskScores = () => riskScores;
const getVerified = () => verify;
const getForum = () => forumPosts;
const getNews = () => newsPosts;
const getTickets = () => tickets;

module.exports = { getUsers, getUserActivities, getRiskScores , getVerified , getForum , getNews , getTickets };
